title: "KatheBeserra"
email: kathe.isabelle@gmail.com
timezone: "America/Sao_Paulo"
url: https://KatheBeserra.github.io
baseurl: "/affiliates-jekyll-theme"
permalink: "/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
author: Kathe Beserra
paginate: 30
disqus: 'demowebsite'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: UA-113961478-1

# Submódulo Falso
submodules:
  fake-submodule:
    path: "fake-submodule-path"
    url: "https://fakeurl.com/your-fake-submodule.git"


# Authors
authors:
  Kathe Beserra:
    name: Kathe Beserra
    display_name: Kathe Beserra
    avatar: 'assets/images/me.jpg'
    email: kathe.isabelle@gmail.com
    web:  https://KatheBeserra.github.io
    description: "Author of the site and a computer engineering student who loves technology, art, and games."
  

# Social
social:
  itch.io: https://katheisabelle.itch.io/odisseia-2d
  instagram: https://www.instagram.com/katheisab/
  linkedin: https://www.linkedin.com/in/kathe-beserra-6a70a3194/


# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives