title: "KatheIsabelle"
email: kathe.isabelle@gmail.com
timezone: "America/Sao_Paulo"
url: https://katheisabelle.github.io
baseurl: ""
permalink: "permalink: /:categories/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
author: Kathe Beserra
paginate: 30
disqus: 'demowebsite'
locale: en_us
lang: en_us
feed_items: 10  
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: UA-113961478-1



# Authors
authors:
  Kathe Beserra:
    name: Kathe Beserra
    display_name: Kathe Beserra
    avatar: 'assets/images/me.jpg'
    email: kathe.isabelle@gmail.com
    web:  https://katheBeserra.github.io
    description: "Author of the site and a computer engineering student who loves technology, art, and games."
  

# Social
social:
  itch.io: https://katheisabelle.itch.io
  github: https://github.com/KatheIsabelle
  instagram: https://www.instagram.com/katheisab/
  linkedin: https://www.linkedin.com/in/kathe-beserra-6a70a3194/
  twitter: https://x.com/maquinadaflo


include:
  - README.md
  - .gitignore
  - assets


# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives
